### ISSUE TITLE
Project roadmap

### ISSUE THREAD

**Issue by kaiquebuilds** [ikeborges/insightful#1]
- [x] Create roadmap
- [x] Define a design and development process
- [x] Document the process
- [x] Update README.md to describe the project.
